CREATE DATABASE bancodeteste;
CREATE TABLE cadastro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  cep VARCHAR(10) NOT NULL,
  local VARCHAR(100) NOT NULL,
  endereco VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  idade INT NOT NULL
);
